version: '3'

services:
  php:
    build:
      context: ./php
    volumes:
      - ./web:/var/www/html
    networks:
      - my_network

  mongodb:
    build:
      context: ./mongodb
    ports:
      - "27017:27017"
    networks:
      - my_network

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./web:/var/www/html
    ports:
      - "8081:80"
    depends_on:
      - php
    networks:
      - my_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my_network

networks:
  my_network:
