version: "3.8"

networks:
  ecomplete:
    driver: bridge

services:
  #--WEBSERVER--#
  webserver:
    build:
      context: ${ROOT_PATH}/docker/apache
    image: ecomplete-webserver
    container_name: ecomplete-webserver
    networks:
      - ecomplete
    ports:
      - ${HOST_PORT_WEBSERVER}:80
      - ${HOST_PORT_WEBSERVER_SSL}:443
    volumes:
      - ${ROOT_PATH}:/var/www/html
      - ${ROOT_PATH}/logs/webserver:/var/log/apache:rw${MOUNT_OPTIONS}
    depends_on:
      #--PHP82--#
      - php82
      #--/PHP82--#
  #--/WEBSERVER--#
  #--PHP82--#
  php82:
    build:
      context: ${ROOT_PATH}/docker/php82
#    command: sh -c "composer install"
    image: ecomplete-php
    container_name: ecomplete-php
    networks:
      - ecomplete
    environment:
      TZ: ${TIMEZONE}
    volumes:
      - ${ROOT_PATH}:/var/www/html
    depends_on:
      #--MYSQL--#
      - mysql
      #--/MYSQL--#
  #--/PHP82--#
  #--MYSQL--#
  mysql:
    #--MYSQL-IMAGE--#
    image: mysql:${MYSQL_VERSION}
    #--/MYSQL-IMAGE--#
    container_name: ecomplete-mysql
    networks:
      - ecomplete
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DEFAULT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DEFAULT_DB}
      MYSQL_ROOT_USER: ${MYSQL_DEFAULT_USER}
      MYSQL_PASSWORD: ${MYSQL_DEFAULT_PASSWORD}
    ports:
      - ${HOST_PORT_MYSQL}:3306
    volumes:
      - ${ROOT_PATH}/docker/mysql/custom.cnf:/etc/mysql/conf.d/local.cnf
      - ${ROOT_PATH}/logs/mysql:/var/log/mysql:rw${MOUNT_OPTIONS}
      - mysql-data:/var/lib/mysql
  #--/MYSQL--#
  #--PHPMYADMIN--#
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION}
    container_name: ecomplete-phpmyadmin
    networks:
      - ecomplete
    depends_on:
      #--PHP82--#
      - php82
      #--/PHP82--#
      - mysql
    ports:
        - ${HOST_PORT_PHPMYADMIN}:80
    environment:
      MYSQL_USERNAME: ${MYSQL_DEFAULT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_DEFAULT_PASSWORD}
      PMA_HOST: mysql
      PMA_PORT: ${HOST_PORT_MYSQL}
  #--/PHPMYADMIN--#
  #--MONGODB--#
  mongodb:
    build:
      context: ${ROOT_PATH}/docker/mongodb
    container_name: ecomplete-mongodb
    ports:
      - ${HOST_PORT_MONGODB}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ADMIN_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ADMIN_PASSWORD}
    networks:
      - ecomplete
  #--/MONGODB--#
volumes:
  #--MYSQL--#
  mysql-data:
    driver: "local"
  #--/MYSQL--#
