version: '3'

services:
  php:
    build:
      context: ./php
    volumes:
      - ./web:/var/www/html
    networks:
      - my_network

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - my_network

networks:
  my_network:
